- .storybook/config.js
- .storybook/lightTheme.js
Now the storybook plays along with the Online theme from figma:
> Make the storybook theme match the Online theme

- package.json
> Changed command to start instead of storybook

- src/components/forms/TextField.stories.mdx
- src/components/forms/TextField.tsx
My input suggestion was too specific. Just removing some weird things to keep it basic.
> Remove unnecessary things from text field

- .drone.yml
- src/components/alerts/Alert.tsx
- src/components/logo/SpinnerLogo.tsx
- src/components/logo/StaticLogo.tsx
We need linting to ensure no one writes bad TS.
> Fix linting

- src/components/shared/global.ts
The markdown titles look kinda ugly, and the fact that there are two really big global styles is kinda ugly, but progress is progress.
> Adds reset css

- src/components/alerts/Alert.tsx
- src/components/container/Container.tsx
Changed all jsx.element to React.ReactNode
> Change jsx.element to reactnode

- .drone.yml
- package.json
- src/components/buttons/ToggleSwitch.tsx
- src/components/forms/TextField.tsx
- src/components/icons/CircleCheckmark.stories.js
- src/components/icons/CircleCheckmark.tsx
- src/components/icons/CircleCross.stories.js
- src/components/icons/CircleCross.tsx
- src/components/logo/StaticLogo.tsx
- src/components/tabs/Tab.tsx
- src/components/tabs/TabSelect.tsx
- src/components/tabs/Tabs.tsx
Make sure we always check for linting errors and format style.
Fixes #71
> Fix lint and format

- .eslintrc.js
- src/components/loading/Loading.stories.mdx
- src/components/loading/Spinner.tsx
- src/index.ts
> Port small spinner from receipt form

- .storybook/config.js
- src/components/alerts/Alert.stories.mdx
- src/components/checkbox/Checkbox.stories.mdx
- src/components/container/Container.stories.mdx
- src/components/eventCard/EventCard.stories.mdx
- src/components/loading/Loading.stories.mdx
- src/components/logo/Logo.stories.mdx
- src/components/select/Select.stories.mdx
- src/components/tabs/Tabs.stories.mdx
- src/components/textField/TextField.stories.mdx
- src/components/toggleSwitch/ToggleSwitch.stories.mdx
Just a proposal on how we can do the categories. Now it is sorted by nothing and we have no structure (categories).
This PR gives us this, which is both sorted and categorized:
> Fix categories

- src/components/breakpoints/Breakpoints.stories.mdx
- src/components/breakpoints/Breakpoints.tsx
- src/components/cards/Card.stories.mdx
- src/components/cards/Card.tsx
- src/index.ts
> Add card to component library

- src/common/global.ts
- src/components/radio/Radio.stories.mdx
- src/components/radio/Radio.tsx
> Adds rudimentary radio button group

- src/common/types.ts
- src/components/alerts/Alert.tsx
- src/components/breakpoints/Breakpoints.tsx
- src/components/button/Button.tsx
- src/components/cards/Card.tsx
- src/components/checkbox/Checkbox.tsx
- src/components/eventCard/EventCard.tsx
- src/components/icons/CircleCheckmark.tsx
- src/components/icons/CircleCross.tsx
- src/components/logo/LightningO.tsx
- src/components/logo/Logo.tsx
- src/components/logo/StaticLogo.tsx
- src/components/logo/StaticSpinnerLogo.tsx
- src/components/radio/Radio.tsx
- src/components/spinner/Spinner.tsx
- src/components/tabs/Tab.tsx
- src/components/tabs/TabHeader.tsx
- src/components/tabs/TabSelect.tsx
- src/components/tabs/Tabs.tsx
- src/components/textField/TextField.tsx
- src/components/toggleSwitch/ToggleSwitch.tsx
> Add missing return types to functions

- src/common/global.ts
- src/components/alerts/Alert.tsx
- src/components/icon/Icon.tsx
also i changed icon style from two-tone to outlined because @plusk has shit taste
Resolves #58
> Added icons to Alert component

- src/components/alerts/Alert.tsx
- src/components/spinner/Spinner.stories.mdx
- src/components/spinner/SpinnerCircles.tsx
shit's tight fam ngl fixes #54
> Added loader from super-duper-fiesta

- src/index.ts
Added components to export file to make them available for usage when using the npm package.
> Refactor component exporting and add missing components

- src/components/textField/TextField.tsx
Removes the border from the ClearButton from the TextField component
relevant issue: #138
> Fix: always removes the border from the ClearButton from the TextField component

- src/components/textArea/TextArea.stories.mdx
- src/components/textArea/TextArea.tsx
- src/index.ts
> Added textarea

- README.md
- src/components/textField/TextField.tsx
- src/index.ts
- src/intro.stories.mdx
> Fixing some stuff for Anhkha's beta test

- src/components/logo/Logo.stories.mdx
I originally wanted to just add an `h`. I think this wording is more fitting, though.
> feat: More buzzwords

- .drone.yml
- package.json
I really really want this feature. We can now see changes in form of images. The only drawback is that it costs [$149/mo](https://www.chromaticqa.com/pricing) :(
Just going to test the trail for 30 days. If people like it, we could look for alternatives. I guess noone wants to pay $149/mo => $1788/yr just for some snapshots once in a while.
> Add chromatic setup for CI

- .drone.yml
- README.md
We do not want to spam our drone server with things that only need to be done once in a while.
> Run chromatic on master merge only

- src/components/checkbox/Checkbox.tsx
Fix an issue @kharann had with using the Checkbox component. When hovering parent elements, all children got blue border when none should have been affected. Do still not exactly understand the problem, as the css used hashes and stuff, but maybe this was the only fix that was needed.
Before:
After:
> Specify checkbox hover selector

- src/components/card/Card.stories.mdx
- src/components/card/Card.tsx
- src/components/eventCard/EventCard.stories.mdx
- src/components/icon/Icon.tsx
- src/components/link/Link.tsx
- src/components/logo/Logo.stories.mdx
- src/components/message/Message.stories.mdx
- src/components/message/Message.tsx
- src/components/select/Select.stories.mdx
This is a combination of minor textual and prop-updates, as part of a consistency check.
With this pull request, the component `Message` should have consistent prop names with other components, and some minor additions like a `style`-prop which the `Card`-story revolved around which were not in the prop-list.
`Message` could still need a textual look-through, a color check, an evaluation of hover- and focus-effect necessity, as well as breakpoints and a11y
...
> Message: consistency and cleaning

- src/components/checkbox/Checkbox.tsx
> Add isChecked prop to styled components

- src/components/checkbox/Checkbox.stories.mdx
> feat(checkbox): changed a word in the text

- src/components/checkbox/Checkbox.stories.mdx
just bumping a version, don't mind me.
> feat(version-bump): adding more text for a commit

- src/components/textField/TextField.tsx
> Set InputField border-sizing

- package.json
- src/index.ts
I checked the box that I had exported the component, but it was a lie 👎
> Add missing radiobutton-export

- package.json
- src/components/checkbox/Checkbox.stories.mdx
- src/components/logo/BlackBackground.tsx
- src/components/logo/CompactLogo.tsx
- src/components/logo/Logo.stories.mdx
> Set logo to match brand identity

- package-lock.json
- package.json
- public/index.html
- src/common/global.ts
- src/components/icon/Icon.tsx
This removes a warning we had about importing in global styles.
> No import in global style

- package-lock.json
- package.json
- src/components/select/Select.stories.mdx
- src/components/select/Select.tsx
OWF needed defaultValue or value on the select tag. So we changed to react-select.
Co-authored-by: FluidSense <johanneskv96@gmail.com>
> Update select to use react-select
